name: Android Build & Deploy

on:
  pull_request:
    branches:
      - master
    types: [synchronize]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    defaults:
      run:
        working-directory: ./android

    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v4

      - name: Set up Node env
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install Ruby dependencies
        run: bundle install

      - name: Install Node dependencies
        run: npm install

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Setup Keystore File
        run: echo "${{secrets.KEYSTORE_FILE}}" | base64 -d > "${{ github.workspace }}/production.keystore"

      - name: Build Android Release
        run: |
          bundle exec fastlane android build_bundle bump_type:"patch" local_env:false
        env:
          KEYSTORE_FILE: '${{ github.workspace }}/production.keystore'
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Increment package version
        run: |
          npm version patch -m "chore: update package version"

      # - name: Push Git Tag
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "<>"
      #     git push origin $NEW_TAG

      - name: Commit and push version change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update version code and version name'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: |
            ${{ github.workspace }}/app/build/outputs/bundle/release
